[package]
name = "reth-dtvm-witness-db"
version = "0.1.0"
edition = "2021"
rust-version = "1.95"
publish = false

[workspace]

[dependencies]
alloy-consensus = { version = "=2.1.1", default-features = false, features = ["std"] }
alloy-eips = { version = "=2.1.1", default-features = false, features = ["std"] }
alloy-evm = { version = "=0.37.1", default-features = false, features = ["std"] }
alloy-primitives = { version = "=1.6.1", default-features = false, features = ["std", "serde"] }
alloy-rlp = { version = "=0.3.16", default-features = false, features = ["std"] }
alloy-rpc-types-debug = { version = "=2.1.1", default-features = false }
alloy-trie = { version = "=0.9.5", default-features = false, features = ["std", "ethereum"] }
libc = "=0.2.189"
reth-chainspec = { path = "../../crates/chainspec" }
reth-consensus = { path = "../../crates/consensus/consensus" }
reth-dtvm-transaction-adapter = { path = "../reth-transaction" }
reth-ethereum-consensus = { path = "../../crates/ethereum/consensus" }
reth-ethereum-primitives = { path = "../../crates/ethereum/primitives" }
reth-evm = { path = "../../crates/evm/evm" }
reth-evm-ethereum = { path = "../../crates/ethereum/evm" }
reth-primitives-traits = { version = "=0.5.2", default-features = false, features = ["std", "secp256k1"] }
reth-trie-common = { path = "../../crates/trie/common" }
reth-trie-sparse = { path = "../../crates/trie/sparse", default-features = false, features = ["std"] }
revm = { version = "=41.0.0", default-features = false, features = ["std"] }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.150"
sha2 = "=0.10.9"
thiserror = "=2.0.18"

[dev-dependencies]
pretty_assertions = "=1.4.1"
reth-dtvm-adapter = { path = ".." }

[patch.crates-io]
revm-handler = { path = "../../patched/revm-handler" }

[profile.dev]
debug = 1
